# Generated by Django 5.1.3 on 2024-11-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gail_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfupload',
            name='file_type',
            field=models.CharField(blank=True, choices=[('stock_point_file', 'STOCK POINT FILE'), ('freight_file', 'FREIGHT FILE'), ('ex_work_file', 'EX WORK FILE')], max_length=64),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='month',
            field=models.CharField(blank=True, choices=[('jan', 'january'), ('feb', 'february'), ('mar', 'march'), ('apr', 'april'), ('may', 'may'), ('jun', 'june'), ('jul', 'july'), ('aug', 'august'), ('sep', 'september'), ('oct', 'october'), ('nov', 'november'), ('dec', 'december')], max_length=64),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2024),
        ),
    ]
