# Generated by Django 5.1.3 on 2025-01-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gail_app', '0002_pdfupload_file_type_pdfupload_month_pdfupload_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='month',
            field=models.CharField(blank=True, choices=[('january', 'january'), ('february', 'february'), ('march', 'march'), ('april', 'april'), ('may', 'may'), ('june', 'june'), ('july', 'july'), ('august', 'august'), ('september', 'september'), ('october', 'october'), ('november', 'november'), ('december', 'december')], max_length=64),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2025),
        ),
    ]
