# Generated by Django 5.1.3 on 2025-05-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gail_app', '0003_alter_pdfupload_month_alter_pdfupload_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='file_type',
            field=models.CharField(blank=True, choices=[('stock_point_file', 'STOCK POINT FILE'), ('freight_file', 'FREIGHT FILE'), ('ex_work_file', 'EX WORK FILE'), ('competitor_file', 'CROSS REFERENC FILE')], max_length=64),
        ),
    ]
