# Generated by Django 5.1.3 on 2025-05-25 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gail_app', '0004_alter_pdfupload_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files/')),
                ('file_type', models.CharField(choices=[('cross_reference', 'Cross Reference File')], default='cross_reference', max_length=64)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gail_grade', models.CharField(max_length=100)),
                ('competitor_name', models.CharField(max_length=100)),
                ('competitor_grade', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excel_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_references', to='gail_app.excelupload')),
            ],
            options={
                'indexes': [models.Index(fields=['gail_grade', 'competitor_name'], name='gail_app_cr_gail_gr_ef2039_idx'), models.Index(fields=['competitor_name', 'competitor_grade'], name='gail_app_cr_competi_b52c15_idx')],
                'unique_together': {('gail_grade', 'competitor_name', 'competitor_grade', 'excel_upload')},
            },
        ),
    ]
