# Generated by Django 5.1.3 on 2025-05-25 06:54

import gail_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gail_app', '0005_excelupload_crossreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelupload',
            name='file',
            field=models.FileField(upload_to='excel_files/', validators=[gail_app.models.validate_excel_file]),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='file',
            field=models.FileField(upload_to='pdfs/', validators=[gail_app.models.validate_pdf_file]),
        ),
    ]
